### PR TITLE
Rewrite library to ES6 style

### PR DESCRIPTION
**Pull request by TheAlexLichter**
This PR updates the library to the newest ES6 style. Also:

+ Replace Requests library with Axios
+ Rewrite method in promise-based style
+ Add default value for "stat" parameter
+ Add tests (with Mocha)
+ Add a Travis-CI config

### CODE REVIEW

**Comment by TheAlexLichter** [comment]
I'm using that version in my own project now and it works out well until now ☺️

**Comment by jestillore** [comment]
Cool. Thanks for this. :)
I was planning on rewriting this to ES6 and now that you've done it already, I'll check this and merge ASAP.
Thanks!

**Comment by TheAlexLichter** [comment]
No problem! Hope everything is as you like it ☺️

**Comment by jestillore** [comment]
Merged. Thanks for your contribution :)

**Pull request merged**
